require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NetCardsController do

  # This should return the minimal set of attributes required to create a valid
  # NetCard. As you add validations to NetCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "applicant_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NetCardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all net_cards as @net_cards" do
      net_card = NetCard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:net_cards).should eq([net_card])
    end
  end

  describe "GET show" do
    it "assigns the requested net_card as @net_card" do
      net_card = NetCard.create! valid_attributes
      get :show, {:id => net_card.to_param}, valid_session
      assigns(:net_card).should eq(net_card)
    end
  end

  describe "GET new" do
    it "assigns a new net_card as @net_card" do
      get :new, {}, valid_session
      assigns(:net_card).should be_a_new(NetCard)
    end
  end

  describe "GET edit" do
    it "assigns the requested net_card as @net_card" do
      net_card = NetCard.create! valid_attributes
      get :edit, {:id => net_card.to_param}, valid_session
      assigns(:net_card).should eq(net_card)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NetCard" do
        expect {
          post :create, {:net_card => valid_attributes}, valid_session
        }.to change(NetCard, :count).by(1)
      end

      it "assigns a newly created net_card as @net_card" do
        post :create, {:net_card => valid_attributes}, valid_session
        assigns(:net_card).should be_a(NetCard)
        assigns(:net_card).should be_persisted
      end

      it "redirects to the created net_card" do
        post :create, {:net_card => valid_attributes}, valid_session
        response.should redirect_to(NetCard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved net_card as @net_card" do
        # Trigger the behavior that occurs when invalid params are submitted
        NetCard.any_instance.stub(:save).and_return(false)
        post :create, {:net_card => { "applicant_id" => "invalid value" }}, valid_session
        assigns(:net_card).should be_a_new(NetCard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NetCard.any_instance.stub(:save).and_return(false)
        post :create, {:net_card => { "applicant_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested net_card" do
        net_card = NetCard.create! valid_attributes
        # Assuming there are no other net_cards in the database, this
        # specifies that the NetCard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NetCard.any_instance.should_receive(:update).with({ "applicant_id" => "1" })
        put :update, {:id => net_card.to_param, :net_card => { "applicant_id" => "1" }}, valid_session
      end

      it "assigns the requested net_card as @net_card" do
        net_card = NetCard.create! valid_attributes
        put :update, {:id => net_card.to_param, :net_card => valid_attributes}, valid_session
        assigns(:net_card).should eq(net_card)
      end

      it "redirects to the net_card" do
        net_card = NetCard.create! valid_attributes
        put :update, {:id => net_card.to_param, :net_card => valid_attributes}, valid_session
        response.should redirect_to(net_card)
      end
    end

    describe "with invalid params" do
      it "assigns the net_card as @net_card" do
        net_card = NetCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NetCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => net_card.to_param, :net_card => { "applicant_id" => "invalid value" }}, valid_session
        assigns(:net_card).should eq(net_card)
      end

      it "re-renders the 'edit' template" do
        net_card = NetCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NetCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => net_card.to_param, :net_card => { "applicant_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested net_card" do
      net_card = NetCard.create! valid_attributes
      expect {
        delete :destroy, {:id => net_card.to_param}, valid_session
      }.to change(NetCard, :count).by(-1)
    end

    it "redirects to the net_cards list" do
      net_card = NetCard.create! valid_attributes
      delete :destroy, {:id => net_card.to_param}, valid_session
      response.should redirect_to(net_cards_url)
    end
  end

end
